spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dio-db?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: Familia308@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true